### ISSUE TITLE
Draw cirlce polygon

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/pariaula12B-profs#5]
![image](https://user-images.githubusercontent.com/11350998/70639759-d5417200-1c32-11ea-90e0-4548f82398de.png)

**Comment by vitoruapt** [comment]
I have done it:
![image](https://user-images.githubusercontent.com/3542250/70641274-4d109c00-1c35-11ea-86e1-76c62171d0f6.png)

Hope this is enough :-)

**Comment by miguelriemoliveira** [comment]
:+1:

**Comment by miguelriemoliveira** [comment]
Hi @vitoruapt you forgot to commit / push your changes. 

The picture looks very nice, I would like to run it in my code as well ...

**Comment by miguelriemoliveira** [comment]
copy from regular polygon code and adapt

**Comment by miguelriemoliveira** [comment]
done in https://github.com/miguelriemoliveira/pariaula12B-profs/commit/1530cd864fefff402c2046467fff8bc7431b8392
